[workspace]
authors = ["Seth Stadick <sstadick@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://repo.prefix.dev/modular-community",
    "https://prefix.dev/pixi-build-backends",
    "conda-forge",
]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[package]
name = "mojo-lapper"
license = "Unlicense OR MIT"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.1.*" }

[tasks]
t = { cmd = "pixi run mojo test -D ASSERT=all -I . tests" }
r = { cmd = "pixi run mojo run -I ." }
bc = { cmd = "pixi run mojo build --march native -I . -o cpu_bench benchmarks/bench_cpu.mojo" }
bg = { cmd = "pixi run mojo build --march native -I . -o gpu_bench benchmarks/bench_gpu.mojo" }
bl = { cmd = "pixi run mojo build --march native -I . -o lapper_bench benchmarks/bench_lapper.mojo" }

[dependencies]
modular = "=25.4.0"
extramojo = "=0.15.0"
rattler-build = "*"
